<svg
    xmlns="http://www.w3.org/2000/svg"
    width="16"
    height="16"
    viewBox="0 0 16 16"
    fill="none"
    aria-hidden="true"
>
    <rect
        x="1"
        y="1"
        width="14"
        height="14"
        rx="3"
        fill="white"
        stroke="#9CA3AF"
        stroke-width="2"
    />
</svg>
